# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
                entity:
                    class: AppBundle:User
                    property: username
                    # if you're using multiple entity managers
                    # manager_name: customer
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
                pattern:   ^/login$
                anonymous: ~
        
        register:
                pattern:   ^/register$
                anonymous: ~
                
        secured_area:
                pattern:    ^/
                # anonymous: ~
                form_login:
                    login_path: login_route
                    check_path: login_check
                provider: our_db_provider
                
                logout:
                    # The route name the user can go to in order to logout
                    path: security_logout
                    # The name of the route to redirect to after logging out
                    target: login_route
                    
                remember_me:
                    secret:   '%secret%'
                    lifetime: 604800 # 1 week in seconds
                    path:     /
                    # by default, the feature is enabled by checking a
                    # checkbox in the login form (see below), uncomment the
                    # following line to always enable it.
                    #always_remember_me: true
                

    
    access_control:
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
            
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_USER:  ROLE_VIEWER

    
        
 
                
