# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.folder_voter:
        class: AppBundle\Security\FolderVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false
        
    app.tag_voter:
        class: AppBundle\Security\TagVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false
    
    app.task_voter:
        class: AppBundle\Security\TaskVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false