<?php

namespace AppBundle\Entity;

/**
 * FolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FolderRepository extends \Doctrine\ORM\EntityRepository
{
}
